#You can use any name
#You can create sections as much as you want
global:
  #servers: [Lobby, BedWars-1, BedWars-2, SkyWars-{1-10}]
  servers: [global]
  #a delay between messages
  interval: 60
  #shufle messages or no
  random: true
  #Placeholders - %player%, %server%
  messages:
    1:
      - "<red>Multi"
      - "<red>line"
    2:
      - "<red>Multi"
      - "<red>line"
    3:
      - "<red>Multi"
      - "<red>line"